name: Build Flutter APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    # Hedha el star el se7ri bch GitHub Actions ma t-blokich el build
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        # Zidtlek --no-pub bch ma i-dhaya3ch el wa9t
        run: flutter build apk --release --no-pub

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: hanchiafish-apk
          path: build/app/outputs/flutter-apk/app-release.apk